### ISSUE TITLE
PasswordBox Overlay does not display by default, and is unselectable once the overlay shows

### ISSUE THREAD

**Issue by JBtje** [JohanLarsson/Gu.Wpf.Adorners#15]
Reproduce:
- Download master
- Set Gu.Wpf.Adorners.Demo as default build
- Go to tab Password, *note, overlay is not showing*
- Select PasswordBox, add text, remove text, lose focus
- Overlay is showing "Write something secret here"
- Click PasswordBox, it is unselectable.

Tab/shift Tab does work however.

Targetframework: 4.5
OS: Win 10 Pro, V1709 (Build 16299.309
VS2017

**Comment by JohanLarsson** [comment]
Thanks for reporting, this does not sound very awesome.

**Comment by JohanLarsson** [comment]
Added support for `Watermark` for `PasswordBox` & `ComboBox`

```xaml
<StackPanel>
    <TextBox adorners:Watermark.Text="Write something here" />

    <PasswordBox adorners:Watermark.Text="Write something here" />

    <ComboBox adorners:Watermark.Text="Write something here">
        <ComboBoxItem>abc</ComboBoxItem>
        <ComboBoxItem>cde</ComboBoxItem>
        <ComboBoxItem>fgh</ComboBoxItem>
    </ComboBox>
</StackPanel>
```

Relöeased an update: https://www.nuget.org/packages/Gu.Wpf.Adorners/1.4.0
