### ISSUE TITLE
problem with ctrlkeys

### ISSUE THREAD

**Issue by tofutim** [JohanLarsson/Gu.Wpf.Adorners#4]
When I press Ctrl Win F1 - I get

![image](https://cloud.githubusercontent.com/assets/157766/13365370/75083a82-dc89-11e5-8327-c8330fb6a5e4.png)

**Comment by tofutim** [comment]
I think it is because there is keyboard input but the box is empty

**Comment by tofutim** [comment]
I tested some more, no problem with anything except Ctrl-Win-F1 (on Mac I press Ctrl-Cmd-Fn-F1). It works with Ctrl-Win-F2. So strange!

**Comment by JohanLarsson** [comment]
Wow, that looks nasty, thanks for reporting the issue. Looks like I dumbed a nullcheck.

**Comment by JohanLarsson** [comment]
I could not repro it in the demo project, gonna read some code now and try to spot the bug.

**Comment by tofutim** [comment]
Maybe it is something else I am doing in my program - will check it.

**Comment by tofutim** [comment]
When I press Ctrl-Win-F1, it switches to a different tab in my TabControl -
that may be the issue

**Comment by JohanLarsson** [comment]
Ah, nice thanks for the info. I added a nullcheck, publishing a package you can try.

**Comment by JohanLarsson** [comment]
[Published 1.1.1.1](https://www.nuget.org/packages/Gu.Wpf.Adorners/1.1.1.1) could not repro it so dunno if fixed.

**Comment by tofutim** [comment]
You saved the day! I just installed 1.1.1.2 and it resolves the issue. Thank you Johan.
