### ISSUE TITLE
Textbox Adorner in Frames

### ISSUE THREAD

**Issue by Eun** [JohanLarsson/Gu.Wpf.Adorners#5]
First of all: Great work, simple to use, does what it should. 👍 

However I have a problem using a frame in a tabcontrol. On the second tab the adorner is only set if you focus the textbox.

Here is the sample:

![sample](https://cloud.githubusercontent.com/assets/796084/20716267/f1795054-b651-11e6-914d-4492f17460bb.gif)

Sample Repo:
https://github.com/Eun/GuWpfAdornersBug

**Comment by JohanLarsson** [comment]
Thanks for the report & repro, beautiful! Do you want to have a go at fixing it?

**Comment by Eun** [comment]
If you can provide some details on how you add the adorners I can try to fix it in some time. But currently I have no clue how your lib works.
I bet you can fix the issue in a short time.

Regarding the issue: Seems like something with the focus (or initial state) is wrong.

**Comment by JohanLarsson** [comment]
Ok, I'll have a look
