### ISSUE TITLE
Memory leak with attached events

### ISSUE THREAD

**Issue by AlabamaCoder** [JohanLarsson/Gu.Wpf.Adorners#8]
It looks like the events used in the overlay keep the UIElements referenced even once they are unloaded. Suggest something like this to fix:
```
private static void OnUnLoaded(object sender, RoutedEventArgs e)
        {
        UpdateIsShowing(sender as DependencyObject);

            var element = sender as UIElement;
            if (element != null)
            {
                element.RemoveHandler(FrameworkElement.SizeChangedEvent, new RoutedEventHandler(OnSizeChanged));
                element.RemoveHandler(FrameworkElement.LoadedEvent, new RoutedEventHandler(OnLoaded));
                element.RemoveHandler(FrameworkElement.UnloadedEvent, new RoutedEventHandler(OnUnLoaded));
                element.RemoveHandler(Visible.IsVisibleChangedEvent, new RoutedEventHandler(OnIsVisibleChanged));
            }
        }
```

**Comment by JohanLarsson** [comment]
Oh, this sounds like a nasty bug, thanks for reporting.
Do you want to create a pull request with the fix or should I fix it?

**Comment by JohanLarsson** [comment]
I could not find a place where we do `element.AddHandler`
I hope that the below code does not leak:

```c#
        static Overlay()
        {
            EventManager.RegisterClassHandler(typeof(UIElement), FrameworkElement.SizeChangedEvent, new RoutedEventHandler(OnSizeChanged));
            Loaded.Track();
            EventManager.RegisterClassHandler(typeof(UIElement), FrameworkElement.LoadedEvent, new RoutedEventHandler(OnLoaded));
            EventManager.RegisterClassHandler(typeof(UIElement), FrameworkElement.UnloadedEvent, new RoutedEventHandler(OnUnLoaded));
            EventManager.RegisterClassHandler(typeof(UIElement), Visible.IsVisibleChangedEvent, new RoutedEventHandler(OnIsVisibleChanged));
        }
```

**Comment by JohanLarsson** [comment]
@AlabamaCoder Can you provide a repro?

**Comment by AlabamaCoder** [comment]
EventManager.RegisterClassHandler appears to be the source of it. It appears to create a hard EventHandler reference to every UIElement (since that is the type requested). I found it in a profiler while hunting memory leaks in one of our apps so I don't really have a repro. I can do a pull request and fix it unless you just want to update with that code I posted.

**Comment by JohanLarsson** [comment]
I would be surprised if RegisterClassHandler leaks when everything is static. I'll have a look so that I did not dumb something.

**Comment by JohanLarsson** [comment]
I'm getting a feeling [this](https://github.com/JohanLarsson/Gu.Wpf.Adorners/blob/master/Gu.Wpf.Adorners/Internals/Loaded.cs#L52) is causing the issue. I'm trying to read the IL now.

**Comment by JohanLarsson** [comment]
I released an update, can you check if it works better?

**Comment by JohanLarsson** [comment]
[This](https://connect.microsoft.com/VisualStudio/feedback/details/511753/window-loadedevent-doesnt-work-properly-when-used-to-register-a-class-event-handler) bug is the reason for all this weirdness.

**Comment by JohanLarsson** [comment]
@AlabamaCoder Published an updated nuget, should be no leaks now. Weak events everywhere.
